import { useEffect, useRef, useState } from "react";
import { ArrowsClockwise, BatteryHigh, Bluetooth, BookOpen, BookmarkSimple, ChartBar, FileArrowUp, FolderSimple, GearSix, GridFour, HardDrive, Lightbulb, ListBullets, MagnifyingGlass, Moon, SlidersHorizontal, Sliders, SunDim, Usb, WifiHigh } from "@phosphor-icons/react";
import "./UiLab.css";

type Screen = "home" | "library" | "reader" | "quick" | "settings";
type SettingsSection = "display" | "reading" | "controls" | "system" | null;
type SettingsPage = SettingsSection | "frontlight" | "sleep" | "sleep-cover" | "sleep-image" | "sleep-text" | "status-bar" | "status-icons" | "refresh" | "font-family" | "font-size" | "line-spacing" | "word-spacing" | "text-smoothness";
type KeyboardRequest = { title: string; value: string; kind: "text" | "time"; onSubmit: (value: string) => void };
type StatusSettings = { battery: boolean; clock: boolean; date: boolean; wifi: boolean; bluetooth: boolean; sync: boolean; usb: boolean; charging: boolean; light: boolean; sleep: boolean; storage: boolean };
type ReaderPreferences = { fontFamily: string; fontSize: number; lineSpacing: number; wordSpacing: number; smoothText: boolean };

const BOOKS = [
  ["The Art of Reading", "M. Ito", "42%"], ["The Long Way Home", "S. Baker", "New"], ["Deep Work", "C. Newport", "18%"],
  ["Notes on Stillness", "R. Amin", "76%"], ["The Practice", "S. Adams", "New"], ["Sketches of Time", "L. Park", "9%"],
] as const;
const APPS = [["Library", BookOpen], ["Bookmarks", BookmarkSimple], ["Stats", ChartBar], ["Files", FolderSimple], ["Companion", FileArrowUp], ["Settings", GearSix]] as const;

export function UiLab() {
  const [screen, setScreen] = useState<Screen>("home");
  const [focusedApp, setFocusedApp] = useState(0);
  const [grid, setGrid] = useState(true);
  const [speed, setSpeed] = useState<"fast" | "clean">("fast");
  const [light, setLight] = useState(32);
  const [darkMode, setDarkMode] = useState(false);
  const [uiScale, setUiScale] = useState<"small" | "normal">("small");
  const [statusSettings, setStatusSettings] = useState<StatusSettings>({ battery: true, clock: true, date: false, wifi: true, bluetooth: false, sync: true, usb: false, charging: false, light: false, sleep: false, storage: false });
  const [settingsPage, setSettingsPage] = useState<SettingsPage>(null);
  const [keyboard, setKeyboard] = useState<KeyboardRequest | null>(null);
  const [deviceScale, setDeviceScale] = useState(1);
  const workbenchRef = useRef<HTMLDivElement>(null);
  const goHome = () => { setKeyboard(null); setScreen("home"); };
  const goBack = () => {
    if (keyboard) { setKeyboard(null); return; }
    if (settingsPage === "frontlight" || settingsPage === "sleep" || settingsPage === "status-bar" || settingsPage === "refresh") { setSettingsPage("display"); return; }
    if (settingsPage === "font-family" || settingsPage === "font-size" || settingsPage === "line-spacing" || settingsPage === "word-spacing" || settingsPage === "text-smoothness") { setSettingsPage("reading"); return; }
    if (settingsPage === "status-icons") { setSettingsPage("status-bar"); return; }
    if (settingsPage === "sleep-cover" || settingsPage === "sleep-image" || settingsPage === "sleep-text") { setSettingsPage("sleep"); return; }
    if (settingsPage) { setSettingsPage(null); return; }
    setScreen((current) => current === "quick" ? "reader" : current === "reader" || current === "library" || current === "settings" ? "home" : "home");
  };
  const openHomeApp = (index: number) => {
    setFocusedApp(index);
    const label = APPS[index][0];
    setScreen(label === "Library" ? "library" : label === "Settings" ? "settings" : "home");
  };
  useEffect(() => {
    function handleKey(event: KeyboardEvent) {
      if (screen !== "home") return;
      const direction = event.key === "ArrowRight" ? 1 : event.key === "ArrowLeft" ? -1 : event.key === "ArrowDown" ? 3 : event.key === "ArrowUp" ? -3 : 0;
      if (direction) {
        event.preventDefault();
        setFocusedApp((current) => Math.max(0, Math.min(APPS.length - 1, current + direction)));
      }
      if (event.key === "Enter" || event.key === " ") {
        event.preventDefault();
        openHomeApp(focusedApp);
      }
    }
    window.addEventListener("keydown", handleKey);
    return () => window.removeEventListener("keydown", handleKey);
  }, [focusedApp, screen]);
  useEffect(() => {
    const updateDeviceScale = () => {
      // The 558px footprint includes the shell and the side hardware keys.
      const availableWidth = workbenchRef.current?.clientWidth ?? window.innerWidth;
      setDeviceScale(Math.min(1, Math.max(.1, availableWidth / 558)));
    };
    updateDeviceScale();
    const observer = new ResizeObserver(updateDeviceScale);
    if (workbenchRef.current) observer.observe(workbenchRef.current);
    return () => observer.disconnect();
  }, []);
  return <section className="ui-lab">
    <div className="ui-lab-intro"><div><p className="eyebrow">Offline design prototype</p><h1>Proink UI Lab</h1><p>Test the real X4 Pro portrait canvas before we change firmware. Nothing here connects to a device or needs the internet.</p></div><div className="ui-lab-controls"><div className="segmented" role="group" aria-label="Refresh preview"><button className={speed === "fast" ? "selected" : ""} onClick={() => setSpeed("fast")}>Fast refresh</button><button className={speed === "clean" ? "selected" : ""} onClick={() => setSpeed("clean")}>Full clean</button></div><p><strong>{speed === "fast" ? "Fast" : "Full"}</strong> preview: {speed === "fast" ? "no animation, partial e-ink update" : "white-flash cleaning pass"}</p></div></div>
    <div className="ui-lab-workbench" ref={workbenchRef}><div className="eink-device-frame" style={{ width: `${558 * deviceScale}px`, height: `${926 * deviceScale}px` }}><div className={`eink-device ${speed === "clean" ? "eink-clean" : ""}`} style={{ left: `${13 * deviceScale}px`, transform: `scale(${deviceScale})` }}><button className="hardware-key hardware-key-left" onClick={goBack} aria-label="Physical Back button" /><button className="hardware-key hardware-key-right-top" onClick={() => setScreen("quick")} aria-label="Physical light button" /><button className="hardware-key hardware-key-right-bottom" onClick={() => openHomeApp(0)} aria-label="Physical Library button" /><div className={`eink-screen ${darkMode ? "eink-dark" : ""} ui-scale-${uiScale}`}><StatusBar settings={statusSettings} />{screen === "home" && <Home focusedApp={focusedApp} onFocus={setFocusedApp} onOpen={openHomeApp} onRead={() => setScreen("reader")} />}{screen === "library" && <Library grid={grid} onGrid={() => setGrid((value) => !value)} onBack={goHome} onKeyboard={setKeyboard} />}{screen === "reader" && <Reader onQuick={() => setScreen("quick")} />}{screen === "quick" && <QuickSettings light={light} onLight={setLight} onBack={() => setScreen("reader")} />}{screen === "settings" && <Settings page={settingsPage} onOpen={setSettingsPage} onBack={goBack} onKeyboard={setKeyboard} darkMode={darkMode} onDarkMode={setDarkMode} uiScale={uiScale} onUiScale={setUiScale} statusSettings={statusSettings} onStatusSettings={setStatusSettings} />}{keyboard && <EinkKeyboard request={keyboard} onClose={() => setKeyboard(null)} />}</div><button className="hardware-home" onClick={goHome} aria-label="Physical Home button" /></div></div><aside className="ui-lab-notes"><p className="eyebrow">Hardware rules</p><h2>Design within the panel</h2><ul><li>Logical display: <strong>480 x 800</strong> portrait.</li><li>Black, white, and light dither only.</li><li>Touch targets: minimum <strong>44 px</strong>.</li><li>Fast refresh for navigation; full refresh after a short cadence.</li></ul><p className="ui-lab-note"><strong>Render contract:</strong> one static redraw per confirmed action, persistent focus instead of press animation, cached metadata before the Home screen opens, and bounded background indexing. Use the arrow keys here to test the launcher focus.</p></aside></div>
  </section>;
}

function StatusBar({ settings }: { settings: StatusSettings }) { const rightIcons = [["wifi", WifiHigh], ["bluetooth", Bluetooth], ["sync", ArrowsClockwise], ["usb", Usb], ["charging", BatteryHigh], ["light", SunDim], ["sleep", Moon], ["storage", HardDrive]] as const; return <header className="eink-status"><span className="status-left">{settings.clock && "10:23"}{settings.date && <em>Sep 05</em>}</span><strong className="proink-wordmark">PRO<span>i</span>NK</strong><span className="status-right">{rightIcons.map(([key, Icon]) => settings[key] && <Icon key={key} size={12} weight="bold" />)}{settings.battery && "82%"}</span></header>; }
function Home({ focusedApp, onFocus, onOpen, onRead }: { focusedApp: number; onFocus: (index: number) => void; onOpen: (index: number) => void; onRead: () => void }) { return <main className="eink-main"><button className="continue-card" onClick={onRead}><span className="continue-kicker">NOW READING</span><div className="continue-body"><span className="home-book-cover"><small>PROINK<br />READS</small><b>The<br />Art of<br />Reading</b><em>M. Ito</em></span><span className="continue-details"><strong>The Art of Reading</strong><span className="book-meta">M. Ito <i /> 42% complete</span><span className="book-progress"><b style={{ width: "42%" }} /></span><span className="book-stats"><span><b>6</b>Sessions</span><span><b>2h 18m</b>Read time</span><span><b>5.4</b>Pages/min</span><span><b>23m</b>Avg session</span><span><b>Sep 02</b>Started</span><span><b>42%</b>Progress</span></span></span></div><span className="reading-rhythm"><span><b>4 days</b>Streak</span><span><b>12</b>Books read</span><span><b>Evening</b>Best time</span><span><b>Sunday</b>Most read</span></span><em>Continue reading</em></button><div className="app-grid">{APPS.map(([label, Icon], index) => <button key={label} className={`app-tile ${focusedApp === index ? "selected" : ""}`} aria-current={focusedApp === index ? "true" : undefined} onFocus={() => onFocus(index)} onClick={() => onOpen(index)}><Icon size={28} weight="regular" /><span>{label}</span></button>)}</div></main>; }
function Library({ grid, onGrid, onBack, onKeyboard }: { grid: boolean; onGrid: () => void; onBack: () => void; onKeyboard: (request: KeyboardRequest) => void }) { const [query, setQuery] = useState(""); const books = BOOKS.filter(([title, author]) => `${title} ${author}`.toLowerCase().includes(query.toLowerCase())); return <main className="eink-main eink-library"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Library</strong><span>{query ? `${books.length} found` : "24 books"}</span></div><div className="library-tools"><button onClick={() => onKeyboard({ title: "Search library", value: query, kind: "text", onSubmit: setQuery })}><MagnifyingGlass size={16} /> {query || "Search"}</button><button onClick={onGrid}>{grid ? <ListBullets size={17} /> : <GridFour size={17} />}</button><button><SlidersHorizontal size={17} /></button></div>{grid ? <div className="book-grid">{books.map(([title, author, progress]) => <button className="book-card" key={title}><span className="book-cover"><b>{title.slice(0, 1)}</b></span><strong>{title}</strong><small>{author} <i /> {progress}</small></button>)}</div> : <div className="book-list">{books.map(([title, author, progress]) => <button key={title}><BookOpen size={18} /><span><strong>{title}</strong><small>{author}</small></span><em>{progress}</em></button>)}</div>}</main>; }
function Reader({ onQuick }: { onQuick: () => void }) { return <main className="eink-reader"><div className="reader-top"><button>‹</button><span>The Art of Reading</span><button onClick={onQuick}><SunDim size={18} /></button></div><p className="reader-chapter">CHAPTER THREE</p><h2>Reading as a practice</h2><p>Attention is not a thing to be captured. It is a place we learn to return to, one page at a time.</p><p>When the page is quiet, the reader has room to notice what matters. A good device should disappear and leave the words behind.</p><footer><span>42%</span><span>Page 86 of 204</span></footer></main>; }
function QuickSettings({ light, onLight, onBack }: { light: number; onLight: (value: number) => void; onBack: () => void }) { return <main className="eink-main eink-quick"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Quick settings</strong></div><section><h2>Front light</h2><div className="setting-options"><button className="active"><SunDim size={20} />Bright</button><button>Soft</button><button>Auto</button><button>Off</button></div><label>Brightness <output>{light}</output><input type="range" min="0" max="100" value={light} onChange={(event) => onLight(Number(event.target.value))} /></label></section><section><h2>Refresh</h2><div className="setting-options"><button className="active">Fast</button><button>Balanced</button><button>Clean</button></div></section><section><h2>Layout</h2><div className="setting-options"><button className="active">Comfort</button><button>Compact</button><button>Large text</button></div></section></main>; }

const SETTINGS = [
  ["display", "Display & Power", "Light, refresh, sleep", Lightbulb], ["reading", "Reading", "Type, layout, reading aids", BookOpen], ["controls", "Controls", "Buttons, touch, shortcuts", Sliders], ["system", "Companion & Device", "Wi-Fi, files, updates", WifiHigh],
] as const;
type SettingRow = readonly [label: string, value: string, choices?: readonly string[]];
const DETAIL: Record<Exclude<SettingsSection, null>, readonly SettingRow[]> = {
  display: [
    ["Front light", "On"], ["Sleep screen", "Book cover"], ["Status bar", "Clock, battery & icons"], ["UI scale", "Small", ["Small", "Normal"]], ["Dark mode", "Off", ["Off", "On"]], ["Refresh clean-up", "Every 10 pages"],
  ],
  reading: [
    ["Font family", "Literata"], ["Font size", "20 px"], ["Line spacing", "110%"], ["Word spacing", "0 px"], ["Text smoothness", "On"],
  ],
  controls: [
    ["Home button", "Home", ["Home", "Library", "Reading stats"]], ["Side buttons", "Page turn", ["Page turn", "Volume", "Disabled"]], ["Power button", "Sleep", ["Sleep", "Bookmark", "Front light"]], ["Long press", "Quick settings", ["Quick settings", "Home", "Disabled"]],
    ["Tap left side", "Previous page", ["Previous page", "Menu", "Disabled"]], ["Tap right side", "Next page", ["Next page", "Menu", "Disabled"]], ["Tap centre", "Reader menu", ["Reader menu", "Bookmark", "Disabled"]], ["Touch reader controls", "On", ["Off", "On"]], ["Swipe navigation", "On", ["Off", "On"]],
  ],
  system: [
    ["Wi-Fi", "Proink Home", ["Off", "Proink Home"]], ["Companion portal", "proink.local"], ["Wireless book transfer", "Ready", ["Off", "Ready"]], ["Calibre wireless", "Off", ["Off", "Ready"]],
    ["Reading sync", "Off", ["Off", "On"]], ["Device name", "Proink X4 Pro"], ["Storage", "6.2 GB free"], ["Files & cache", "Manage"], ["Software update", "Up to date"], ["About Proink", "v0.2.0"],
  ],
};
function Settings({ page, onOpen, onBack, onKeyboard, darkMode, onDarkMode, uiScale, onUiScale, statusSettings, onStatusSettings }: { page: SettingsPage; onOpen: (page: SettingsPage) => void; onBack: () => void; onKeyboard: (request: KeyboardRequest) => void; darkMode: boolean; onDarkMode: (value: boolean) => void; uiScale: "small" | "normal"; onUiScale: (value: "small" | "normal") => void; statusSettings: StatusSettings; onStatusSettings: (settings: StatusSettings) => void }) {
  const [refreshChoice, setRefreshChoice] = useState("10 pages");
  const [readerPreferences, setReaderPreferences] = useState<ReaderPreferences>({ fontFamily: "Literata", fontSize: 20, lineSpacing: 110, wordSpacing: 0, smoothText: true });
  if (page === "frontlight") return <FrontLight onBack={onBack} onKeyboard={onKeyboard} />;
  if (page === "sleep") return <SleepScreen onOpen={onOpen} onBack={onBack} />;
  if (page === "sleep-cover") return <SleepCoverPicker onBack={onBack} />;
  if (page === "sleep-image") return <SleepImagePicker onBack={onBack} />;
  if (page === "sleep-text") return <SleepTextEditor onBack={onBack} onKeyboard={onKeyboard} />;
  if (page === "status-bar") return <StatusBarSettings onOpen={onOpen} onBack={onBack} settings={statusSettings} onSettings={onStatusSettings} />;
  if (page === "status-icons") return <StatusIcons onBack={onBack} settings={statusSettings} onSettings={onStatusSettings} />;
  if (page === "font-family") return <FontFamily onBack={onBack} preferences={readerPreferences} onPreferences={setReaderPreferences} />;
  if (page === "font-size") return <ReaderAdjustment title="Font size" label="Size" value={readerPreferences.fontSize} min={12} max={28} step={1} unit="px" onBack={onBack} onCommit={(fontSize) => setReaderPreferences((current) => ({ ...current, fontSize }))} />;
  if (page === "line-spacing") return <ReaderAdjustment title="Line spacing" label="Space between lines" value={readerPreferences.lineSpacing} min={70} max={200} step={5} unit="%" onBack={onBack} onCommit={(lineSpacing) => setReaderPreferences((current) => ({ ...current, lineSpacing }))} />;
  if (page === "word-spacing") return <ReaderAdjustment title="Word spacing" label="Space between words" value={readerPreferences.wordSpacing} min={-2} max={8} step={1} unit="px" onBack={onBack} onCommit={(wordSpacing) => setReaderPreferences((current) => ({ ...current, wordSpacing }))} />;
  if (page === "text-smoothness") return <TextSmoothness onBack={onBack} preferences={readerPreferences} onPreferences={setReaderPreferences} />;
  if (page === "refresh") return <><SettingsDetail section="display" onOpen={onOpen} onBack={onBack} refreshChoice={refreshChoice} darkMode={darkMode} onDarkMode={onDarkMode} uiScale={uiScale} onUiScale={onUiScale} /><RefreshDialog choice={refreshChoice} onApply={(choice) => { setRefreshChoice(choice); onOpen("display"); }} /></>;
  if (page === "reading") return <ReaderSettings onOpen={onOpen} onBack={onBack} preferences={readerPreferences} />;
  if (page) return <SettingsDetail section={page} onOpen={onOpen} onBack={onBack} refreshChoice={refreshChoice} darkMode={darkMode} onDarkMode={onDarkMode} uiScale={uiScale} onUiScale={onUiScale} />;
  return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Settings</strong></div><p className="settings-intro">Make the reader feel like yours.</p><div className="settings-menu">{SETTINGS.map(([id, title, note, Icon]) => <button key={id} onClick={() => onOpen(id)}><Icon size={23} /><span><strong>{title}</strong><small>{note}</small></span><b>›</b></button>)}</div></main>;
}
function ReaderSettings({ onOpen, onBack, preferences }: { onOpen: (page: SettingsPage) => void; onBack: () => void; preferences: ReaderPreferences }) {
  const rows: readonly [SettingsPage, string, string][] = [["font-family", "Font family", preferences.fontFamily], ["font-size", "Font size", `${preferences.fontSize} px`], ["line-spacing", "Line spacing", `${preferences.lineSpacing}%`], ["word-spacing", "Word spacing", `${preferences.wordSpacing} px`], ["text-smoothness", "Text smoothness", preferences.smoothText ? "On" : "Off"]];
  return <main className="eink-main eink-settings reader-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Reading</strong></div><p className="settings-intro">Typography and page rhythm.</p><div className="settings-detail">{rows.map(([page, label, value]) => <button key={page} onClick={() => onOpen(page)}><span><strong>{label}</strong><small>{value}</small></span><b>›</b></button>)}</div></main>;
}
function FontFamily({ onBack, preferences, onPreferences }: { onBack: () => void; preferences: ReaderPreferences; onPreferences: (preferences: ReaderPreferences) => void }) {
  const fonts = ["Literata", "Bitter", "Atkinson Hyperlegible", "OpenDyslexic", "SD: Ember Mono"] as const;
  const fontClass = preferences.fontFamily.toLowerCase().replaceAll(" ", "-").replaceAll(":", "");
  return <main className="eink-main eink-settings font-family-page"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Font family</strong></div><p className={`font-family-sample ${fontClass}`}>The quick brown fox jumps over the lazy dog.</p><p className="settings-intro">Preview &quot;{preferences.fontFamily}&quot;</p><div className="font-family-list">{fonts.map((font) => <button key={font} className={preferences.fontFamily === font ? "selected" : ""} onClick={() => onPreferences({ ...preferences, fontFamily: font })}><span className={font.toLowerCase().replaceAll(" ", "-").replaceAll(":", "")}>{font}</span><b>{preferences.fontFamily === font ? "Selected" : "Preview"}</b></button>)}</div><small className="font-source-note">Built-in fonts and compatible fonts in Fonts/ on the SD card appear here.</small></main>;
}
function ReaderAdjustment({ title, label, value, min, max, step, unit, onBack, onCommit }: { title: string; label: string; value: number; min: number; max: number; step: number; unit: string; onBack: () => void; onCommit: (value: number) => void }) {
  const [draft, setDraft] = useState(value);
  const change = (amount: number) => setDraft((current) => Math.max(min, Math.min(max, current + amount)));
  return <main className="eink-main eink-settings reader-adjustment"><div className="screen-title"><button onClick={onBack}>‹</button><strong>{title}</strong></div><p className="reader-adjustment-preview" style={{ fontSize: title === "Font size" ? `${draft}px` : undefined, lineHeight: title === "Line spacing" ? draft / 100 : undefined, wordSpacing: title === "Word spacing" ? `${draft}px` : undefined }}>A quiet page makes room for the words that matter.</p><section><output>{draft}{unit}</output><div className="reader-adjustment-control"><button onClick={() => change(-step)} aria-label={`Decrease ${label}`}>−</button><input type="range" min={min} max={max} step={step} value={draft} onChange={(event) => setDraft(Number(event.target.value))} aria-label={label} /><button onClick={() => change(step)} aria-label={`Increase ${label}`}>+</button></div><div className="reader-adjustment-range"><span>{min}{unit}</span><span>{max}{unit}</span></div></section><div className="reader-adjustment-actions"><button className="primary" onClick={() => { onCommit(draft); onBack(); }}>Confirm</button><button onClick={onBack}>Cancel</button></div></main>;
}
function TextSmoothness({ onBack, preferences, onPreferences }: { onBack: () => void; preferences: ReaderPreferences; onPreferences: (preferences: ReaderPreferences) => void }) { return <main className="eink-main eink-settings text-smoothness"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Text smoothness</strong></div><p className="reader-adjustment-preview">Reading should feel calm, crisp, and easy on the eyes.</p><button className="setting-toggle" onClick={() => onPreferences({ ...preferences, smoothText: !preferences.smoothText })}><span><strong>Text smoothness</strong><small>{preferences.smoothText ? "Softer letter edges for small text" : "Sharper letter edges with more contrast"}</small></span><i className={preferences.smoothText ? "switch on" : "switch"} /></button><p className="settings-intro">Text smoothness is the plain-language name for anti-aliasing. On e-ink it blends letter edges; turning it off makes text crisper but can look more jagged.</p></main>; }
function SettingsDetail({ section, onOpen, onBack, refreshChoice, darkMode, onDarkMode, uiScale, onUiScale }: { section: Exclude<SettingsSection, null>; onOpen: (page: SettingsPage) => void; onBack: () => void; refreshChoice?: string; darkMode: boolean; onDarkMode: (value: boolean) => void; uiScale: "small" | "normal"; onUiScale: (value: "small" | "normal") => void }) {
  const [values, setValues] = useState<Record<string, string>>({});
  const title = SETTINGS.find(([id]) => id === section)?.[1] ?? "Settings";
  const openDedicatedPage = (label: string): SettingsPage => label === "Front light" ? "frontlight" : label === "Sleep screen" ? "sleep" : label === "Status bar" ? "status-bar" : label === "Refresh clean-up" ? "refresh" : null;
  return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>{title}</strong></div><p className="settings-intro">Tap a setting to preview its next choice.</p><div className="settings-detail">{DETAIL[section].map(([label, initial, choices]) => { const initialValue = label === "Refresh clean-up" && refreshChoice ? refreshChoice : label === "Dark mode" ? darkMode ? "On" : "Off" : label === "UI scale" ? `${uiScale.charAt(0).toUpperCase()}${uiScale.slice(1)}` : initial; const value = values[label] ?? initialValue; const dedicatedPage = openDedicatedPage(label); const isToggle = choices?.length === 2 && choices.includes("Off") && choices.includes("On"); return <button key={label} onClick={() => dedicatedPage ? onOpen(dedicatedPage) : label === "Dark mode" ? onDarkMode(!darkMode) : label === "UI scale" ? onUiScale(value === "Small" ? "normal" : "small") : choices && setValues((current) => ({ ...current, [label]: choices[(choices.indexOf(value) + 1) % choices.length] }))}><span><strong>{label}</strong><small>{value}</small></span>{isToggle ? <i className={value === "On" ? "switch on" : "switch"} /> : choices || dedicatedPage ? <b>›</b> : <em>Info</em>}</button>; })}</div></main>;
}
function FrontLight({ onBack, onKeyboard }: { onBack: () => void; onKeyboard: (request: KeyboardRequest) => void }) {
  const [enabled, setEnabled] = useState(true); const [brightness, setBrightness] = useState(32); const [warmth, setWarmth] = useState(0); const [scheduled, setScheduled] = useState(true); const [start, setStart] = useState("8:00 PM"); const [end, setEnd] = useState("7:00 AM");
  const change = (value: number, setValue: (value: number) => void, amount: number) => setValue(Math.max(0, Math.min(100, value + amount)));
  return <main className="eink-main eink-settings eink-frontlight"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Front light</strong></div><p className="settings-intro">Display & Power / Front light</p><button className="setting-toggle" onClick={() => setEnabled((value) => !value)}><span><strong>Front light</strong><small>{enabled ? "On" : "Off"}</small></span><i className={enabled ? "switch on" : "switch"} /></button><fieldset disabled={!enabled} className="light-controls"><LightControl symbol="☼" label="Brightness" value={brightness} onChange={setBrightness} onStep={(amount) => change(brightness, setBrightness, amount)} /><LightControl symbol="°" label="Warmth" value={warmth} onChange={setWarmth} onStep={(amount) => change(warmth, setWarmth, amount)} /></fieldset><section className="schedule-card"><button className="setting-toggle" onClick={() => setScheduled((value) => !value)}><span><strong>Schedule</strong><small>{scheduled ? "Front light follows this schedule" : "Off"}</small></span><i className={scheduled ? "switch on" : "switch"} /></button><button disabled={!scheduled} onClick={() => onKeyboard({ title: "Start light", value: start, kind: "time", onSubmit: setStart })}><span>Start light</span><b>{start}</b></button><button disabled={!scheduled} onClick={() => onKeyboard({ title: "End light", value: end, kind: "time", onSubmit: setEnd })}><span>End light</span><b>{end}</b></button></section></main>;
}
function LightControl({ symbol, label, value, onChange, onStep }: { symbol: string; label: string; value: number; onChange: (value: number) => void; onStep: (amount: number) => void }) { return <label className="light-control"><b className="light-symbol">{symbol}</b><button type="button" onClick={() => onStep(-5)} aria-label={`Lower ${label}`}>−</button><input type="range" min="0" max="100" step="1" value={value} onChange={(event) => onChange(Number(event.target.value))} aria-label={label} style={{ background: `linear-gradient(to right, #181817 0 ${value}%, transparent ${value}% 100%)` }} /><button type="button" onClick={() => onStep(5)} aria-label={`Raise ${label}`}>+</button><output>{value}</output></label>; }
function SleepScreen({ onOpen, onBack }: { onOpen: (page: SettingsPage) => void; onBack: () => void }) { const [sleepAfter, setSleepAfter] = useState("2 min"); const afterChoices = ["30 sec", "1 min", "2 min", "5 min", "Never"]; return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Sleep screen</strong></div><p className="settings-intro">Choose what the reader shows while it rests.</p><button className="sleep-after" onClick={() => setSleepAfter((value) => afterChoices[(afterChoices.indexOf(value) + 1) % afterChoices.length])}><span><strong>Sleep after</strong><small>Tap to choose timeout</small></span><b>{sleepAfter}</b></button><div className="sleep-choices"><button className="selected" onClick={() => onOpen("sleep-cover")}><b>Book<br />cover</b><span><strong>Book cover</strong><small>Select any title from Books/</small></span></button><button onClick={() => onOpen("sleep-image")}><b className="image-mark">▧</b><span><strong>Image from files</strong><small>Choose from Images/</small></span></button><button onClick={() => onOpen("sleep-text")}><b className="text-mark">Aa</b><span><strong>Styled text</strong><small>Message, template, and font</small></span></button></div></main>; }
function StatusBarSettings({ onOpen, onBack, settings, onSettings }: { onOpen: (page: SettingsPage) => void; onBack: () => void; settings: StatusSettings; onSettings: (settings: StatusSettings) => void }) { const toggle = (key: "battery" | "clock" | "date") => onSettings({ ...settings, [key]: !settings[key] }); const row = (key: "battery" | "clock" | "date", label: string, note: string) => <button className="status-toggle" onClick={() => toggle(key)}><span><strong>{label}</strong><small>{note}</small></span><i className={settings[key] ? "switch on" : "switch"} /></button>; return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Status bar</strong></div><p className="settings-intro">Changes appear in the header immediately.</p><div className="status-controls">{row("battery", "Show battery %", "82%")}{row("clock", "Show clock", "10:23")}{row("date", "Show date", "Sep 05")}</div><button className="status-icons-link" onClick={() => onOpen("status-icons")}><span><strong>Status icons</strong><small>Connection, power, activity & alerts</small></span><b>›</b></button></main>; }
function StatusIcons({ onBack, settings, onSettings }: { onBack: () => void; settings: StatusSettings; onSettings: (settings: StatusSettings) => void }) { const icons = [["wifi", "Wi-Fi", "Signal and connection", WifiHigh], ["bluetooth", "Bluetooth", "Connected accessory", Bluetooth], ["sync", "Sync", "Companion activity", ArrowsClockwise], ["usb", "USB", "Wired connection", Usb], ["charging", "Charging", "Power connected", BatteryHigh], ["light", "Front light", "Light is active", SunDim], ["sleep", "Sleep timer", "Scheduled sleep", Moon], ["storage", "Storage alert", "Low-space warning", HardDrive]] as const; return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Status icons</strong></div><p className="settings-intro">Only enabled icons appear on the right of the header.</p><div className="status-controls icon-controls">{icons.map(([key, label, note, Icon]) => <button className="status-toggle" key={key} onClick={() => onSettings({ ...settings, [key]: !settings[key] })}><Icon size={20} weight="regular" /><span><strong>{label}</strong><small>{note}</small></span><i className={settings[key] ? "switch on" : "switch"} /></button>)}</div></main>; }
function RefreshDialog({ choice, onApply }: { choice: string; onApply: (choice: string) => void }) { const [selected, setSelected] = useState(choice); const options = ["1 page", "5 pages", "10 pages", "15 pages", "30 pages", "Never"]; return <section className="eink-dialog" role="dialog" aria-label="Refresh clean-up"><div><p className="eyebrow">Display & Power</p><h2>Refresh clean-up</h2><p>A full clean redraw clears ghosting after page turns.</p><div className="dialog-options">{options.map((option) => <button className={selected === option ? "selected" : ""} onClick={() => setSelected(option)} key={option}>{option}</button>)}</div><button className="dialog-done" onClick={() => onApply(selected)}>Done</button></div></section>; }
function SleepCoverPicker({ onBack }: { onBack: () => void }) { const [selected, setSelected] = useState("The Art of Reading"); return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Book cover</strong></div><p className="settings-intro">Books/ · use a cover from your library.</p><div className="sleep-picker">{BOOKS.slice(0, 4).map(([title, author]) => <button key={title} className={selected === title ? "selected" : ""} onClick={() => setSelected(title)}><span className="mini-cover">{title.slice(0, 1)}</span><span><strong>{title}</strong><small>{author}</small></span><i className={selected === title ? "switch on" : "switch"} /></button>)}</div></main>; }
function SleepImagePicker({ onBack }: { onBack: () => void }) { const [selected, setSelected] = useState("quiet-forest.webp"); const images = [["quiet-forest.webp", "WEBP · 800 × 1200"], ["reading-room.jpg", "JPEG · 1200 × 1600"], ["paper-texture.png", "PNG · 800 × 1200"], ["night-sky.bmp", "BMP · 800 × 1200"]] as const; return <main className="eink-main eink-settings"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Image from files</strong></div><p className="settings-intro">Images/ · supported: JPG, PNG, WEBP, BMP.</p><div className="sleep-picker">{images.map(([name, detail]) => <button key={name} className={selected === name ? "selected" : ""} onClick={() => setSelected(name)}><span className="mini-image">▧</span><span><strong>{name}</strong><small>{detail}</small></span><i className={selected === name ? "switch on" : "switch"} /></button>)}</div></main>; }
function SleepTextEditor({ onBack, onKeyboard }: { onBack: () => void; onKeyboard: (request: KeyboardRequest) => void }) { const [text, setText] = useState("Rest well.\nA new chapter waits."); const [template, setTemplate] = useState("Quiet"); const [font, setFont] = useState("Press Start 2P"); const templates = ["Quiet", "Quote", "Minimal"] as const; const fonts = ["Press Start 2P", "Literata", "Atkinson", "SD: Ember Mono"] as const; return <main className="eink-main eink-settings eink-sleep-text"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Styled text</strong></div><p className="settings-intro">Fonts/ · SD fonts appear alongside built-ins.</p><button className="text-entry" onClick={() => onKeyboard({ title: "Sleep screen text", value: text, kind: "text", onSubmit: setText })}>{text}</button><div className="choice-row">{templates.map((item) => <button className={template === item ? "selected" : ""} onClick={() => setTemplate(item)} key={item}>{item}</button>)}</div><div className="choice-row font-row">{fonts.map((item) => <button className={font === item ? "selected" : ""} onClick={() => setFont(item)} key={item}>{item}</button>)}</div><output className={`sleep-preview ${template.toLowerCase()}`}>{text}</output></main>; }
function EinkKeyboard({ request, onClose }: { request: KeyboardRequest; onClose: () => void }) { const [value, setValue] = useState(request.value); const [shift, setShift] = useState(false); const [symbols, setSymbols] = useState(request.kind === "time"); const letters = ["qwertyuiop", "asdfghjkl", "zxcvbnm"]; const symbolRows = ["1234567890", "@#$_&-+()", "*/\"':;!?\""]; const append = (key: string) => setValue((current) => `${current}${key}`); const apply = () => { request.onSubmit(value.trim()); onClose(); }; const row = (keys: string, className = "") => <div className={`keyboard-row ${className}`}>{keys.split("").map((key) => <button key={key} onClick={() => append(shift && !symbols ? key.toUpperCase() : key)}><span>{key}</span>{symbols && key >= "0" && key <= "9" && <small>{["!", "@", "#", "$", "%", "^", "&", "*", "(", ")"][Number(key) - 1] ?? ""}</small>}</button>)}</div>; return <section className="eink-keyboard" aria-label={`${request.title} keyboard`}><div className="keyboard-heading"><strong>{request.title}</strong><button onClick={onClose}>Cancel</button></div><input value={value} onChange={(event) => setValue(event.target.value)} autoFocus aria-label={request.title} /><p className="keyboard-tip"><b>Tips:</b> Tap Shift for uppercase. Use ?123 for symbols.</p>{symbols ? <>{row(symbolRows[0])}{row(symbolRows[1])}{row(symbolRows[2])}</> : <>{row("1234567890", "number-row")}{letters.slice(0, 2).map((keys) => row(keys))}<div className="keyboard-row shift-row"><button className={shift ? "key-shift active" : "key-shift"} onClick={() => setShift((value) => !value)}>Shift</button>{letters[2].split("").map((key) => <button key={key} onClick={() => append(shift ? key.toUpperCase() : key)}>{shift ? key.toUpperCase() : key}</button>)}<button className="key-backspace" onClick={() => setValue((current) => current.slice(0, -1))}>⌫</button></div></>}<div className="keyboard-row keyboard-bottom"><button onClick={() => setSymbols((value) => !value)}>{symbols ? "ABC" : "?123"}</button><button className="key-space" onClick={() => append(" ")} /><button className="key-apply" onClick={apply}>OK</button></div></section>; }
