import { useState } from "react";
import { BookOpen, BookmarkSimple, ChartBar, FileArrowUp, FolderSimple, GearSix, GridFour, ListBullets, MagnifyingGlass, SlidersHorizontal, SunDim, WifiHigh } from "@phosphor-icons/react";
import "./UiLab.css";

type Screen = "home" | "library" | "reader" | "quick";

const BOOKS = [
  ["The Art of Reading", "M. Ito", "42%"], ["The Long Way Home", "S. Baker", "New"], ["Deep Work", "C. Newport", "18%"],
  ["Notes on Stillness", "R. Amin", "76%"], ["The Practice", "S. Adams", "New"], ["Sketches of Time", "L. Park", "9%"],
] as const;
const APPS = [["Library", BookOpen], ["Bookmarks", BookmarkSimple], ["Files", FolderSimple], ["Transfer", FileArrowUp], ["Reading", ChartBar], ["Settings", GearSix]] as const;

export function UiLab() {
  const [screen, setScreen] = useState<Screen>("home");
  const [grid, setGrid] = useState(true);
  const [speed, setSpeed] = useState<"fast" | "clean">("fast");
  const [light, setLight] = useState(32);
  return <section className="ui-lab">
    <div className="ui-lab-intro"><div><p className="eyebrow">Offline design prototype</p><h1>Proink UI Lab</h1><p>Test the real X4 Pro portrait canvas before we change firmware. Nothing here connects to a device or needs the internet.</p></div><div className="ui-lab-controls"><div className="segmented" role="group" aria-label="Refresh preview"><button className={speed === "fast" ? "selected" : ""} onClick={() => setSpeed("fast")}>Fast refresh</button><button className={speed === "clean" ? "selected" : ""} onClick={() => setSpeed("clean")}>Full clean</button></div><p><strong>{speed === "fast" ? "Fast" : "Full"}</strong> preview: {speed === "fast" ? "no animation, partial e-ink update" : "white-flash cleaning pass"}</p></div></div>
    <div className="ui-lab-workbench"><div className={`eink-device ${speed === "clean" ? "eink-clean" : ""}`}><div className="eink-screen"><StatusBar />{screen === "home" && <Home onOpen={setScreen} />}{screen === "library" && <Library grid={grid} onGrid={() => setGrid((value) => !value)} onBack={() => setScreen("home")} />}{screen === "reader" && <Reader onQuick={() => setScreen("quick")} />}{screen === "quick" && <QuickSettings light={light} onLight={setLight} onBack={() => setScreen("reader")} />}</div></div><aside className="ui-lab-notes"><p className="eyebrow">Hardware rules</p><h2>Design within the panel</h2><ul><li>Logical display: <strong>480 x 800</strong> portrait.</li><li>Black, white, and light dither only.</li><li>No scrolling carousels, transparency, or live animation.</li><li>Touch targets: minimum <strong>44 px</strong>.</li><li>Fast refresh for navigation; full refresh after a short cadence.</li></ul><p className="ui-lab-note">Use the screens above as a click-through specification. Once the flow feels right, we implement the selected parts in firmware exactly, rather than guessing on the device.</p></aside></div>
  </section>;
}

function StatusBar() { return <header className="eink-status"><span>10:23</span><strong className="proink-wordmark">Pro<span>i</span>nk</strong><span><WifiHigh size={13} weight="bold" /> 82%</span></header>; }
function Home({ onOpen }: { onOpen: (screen: Screen) => void }) { return <main className="eink-main"><button className="continue-card" onClick={() => onOpen("reader")}><span className="continue-kicker">CONTINUE READING</span><strong>The Art of Reading</strong><span>M. Ito <i /> 42%</span></button><div className="home-pulse"><strong>2h 18m</strong><span>this week</span><strong>4 days</strong><span>reading streak</span></div><div className="app-grid">{APPS.map(([label, Icon]) => <button key={label} className="app-tile" onClick={() => onOpen(label === "Library" ? "library" : label === "Settings" ? "quick" : "home")}><Icon size={29} weight="regular" /><span>{label}</span></button>)}</div></main>; }
function Library({ grid, onGrid, onBack }: { grid: boolean; onGrid: () => void; onBack: () => void }) { return <main className="eink-main eink-library"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Library</strong><span>24 books</span></div><div className="library-tools"><button><MagnifyingGlass size={16} /> Search</button><button onClick={onGrid}>{grid ? <ListBullets size={17} /> : <GridFour size={17} />}</button><button><SlidersHorizontal size={17} /></button></div>{grid ? <div className="book-grid">{BOOKS.map(([title, author, progress]) => <button className="book-card" key={title}><span className="book-cover"><b>{title.slice(0, 1)}</b></span><strong>{title}</strong><small>{author} <i /> {progress}</small></button>)}</div> : <div className="book-list">{BOOKS.map(([title, author, progress]) => <button key={title}><BookOpen size={18} /><span><strong>{title}</strong><small>{author}</small></span><em>{progress}</em></button>)}</div>}</main>; }
function Reader({ onQuick }: { onQuick: () => void }) { return <main className="eink-reader"><div className="reader-top"><button>‹</button><span>The Art of Reading</span><button onClick={onQuick}><SunDim size={18} /></button></div><p className="reader-chapter">CHAPTER THREE</p><h2>Reading as a practice</h2><p>Attention is not a thing to be captured. It is a place we learn to return to, one page at a time.</p><p>When the page is quiet, the reader has room to notice what matters. A good device should disappear and leave the words behind.</p><footer><span>42%</span><span>Page 86 of 204</span></footer></main>; }
function QuickSettings({ light, onLight, onBack }: { light: number; onLight: (value: number) => void; onBack: () => void }) { return <main className="eink-main eink-quick"><div className="screen-title"><button onClick={onBack}>‹</button><strong>Quick settings</strong></div><section><h2>Front light</h2><div className="setting-options"><button className="active"><SunDim size={20} />Bright</button><button>Soft</button><button>Auto</button><button>Off</button></div><label>Brightness <output>{light}</output><input type="range" min="0" max="100" value={light} onChange={(event) => onLight(Number(event.target.value))} /></label></section><section><h2>Refresh</h2><div className="setting-options"><button className="active">Fast</button><button>Balanced</button><button>Clean</button></div></section><section><h2>Layout</h2><div className="setting-options"><button className="active">Comfort</button><button>Compact</button><button>Large text</button></div></section></main>; }
